In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5,2)

array([[0.19636604, 0.49646973],
       [0.68045994, 0.39449873],
       [0.85634479, 0.17924352],
       [0.3039271 , 0.33238346],
       [0.79246384, 0.77684771]])

In [27]:
np.random.randn(10)

array([ 0.23805545,  0.20793286,  0.67169072,  0.90251003, -1.28772159,
       -1.54433849,  1.14534396,  0.85686601, -0.1920254 , -1.07673598])

In [28]:
np.random.randn(2,3)

array([[-0.48611331, -0.99245898,  0.47964655],
       [ 0.68046355,  0.02948204, -1.009558  ]])

In [30]:
np.random.randint(0,101,(4,5))

array([[81, 19, 24, 53, 49],
       [29, 46, 11, 83, 90],
       [64, 76, 62, 64, 58],
       [78, 12, 63, 69, 26]])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(0,25)

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr = np.random.randint(0,101,10)

In [36]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [37]:
ranarr.max()

99

In [38]:
ranarr.min()

2

In [39]:
ranarr.argmax()

5

In [40]:
ranarr.argmin()

7

In [42]:
ranarr.dtype

dtype('int32')

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.shape

(5, 5)

In [49]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
myarray = np.linspace(0,10,101)

In [63]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])